# Generated by Django 2.1.5 on 2021-09-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
