# Generated by Django 2.1.5 on 2021-09-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
