# Generated by Django 3.2 on 2022-01-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220124_1053'),
    ]

    operations = [
    ]
