# Generated by Django 2.1.5 on 2021-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210922_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
