# Generated by Django 2.1.5 on 2021-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210922_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('organisation', models.TextField()),
                ('group', models.TextField()),
                ('team', models.TextField()),
                ('role', models.TextField()),
                ('tele_no', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Project', 'PROJECT'), ('Programme', 'PROGRAMME'), ('Portfolio', 'PORTFOLIO')], max_length=20),
        ),
    ]
