# Generated by Django 3.2 on 2022-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='scope',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
