# Generated by Django 3.2 on 2022-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220315_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='type',
            field=models.CharField(choices=[('Project', 'PROJECT'), ('Programme', 'PROGRAMME'), ('Portfolio', 'PORTFOLIO'), ('Department', 'DEPARTMENT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Project', 'PROJECT'), ('Programme', 'PROGRAMME'), ('Portfolio', 'PORTFOLIO'), ('Department', 'DEPARTMENT')], max_length=20),
        ),
    ]
