# Generated by Django 2.1.5 on 2021-09-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210927_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
