# Generated by Django 2.1.5 on 2021-09-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_stakeholder_live'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stakeholder',
        ),
    ]
