# Generated by Django 2.1.5 on 2021-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('tele_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('live', models.BooleanField(default=True)),
            ],
        ),
    ]
