# Generated by Django 3.2 on 2022-09-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppdds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPDDDivison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='historicalppdd',
            name='division',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ppdds.ppdddivison'),
        ),
        migrations.AddField(
            model_name='ppdd',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppdds.ppdddivison'),
        ),
    ]
