# Generated by Django 3.2 on 2021-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppdds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppdd',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
