# Generated by Django 3.2 on 2022-02-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppdds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppdd',
            options={'ordering': ('first_name',)},
        ),
    ]
