# Generated by Django 3.2 on 2022-09-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppdds', '0002_auto_20220915_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppdd',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppdds.ppdddivison'),
        ),
    ]
