# Generated by Django 3.2 on 2022-09-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppdds', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ideas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
