alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: william.grant@dft.gov.uk
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: will_super
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:vWg/Rol9Q5JTTvGTqwa0YjxCHwG7bkxv:yhhrpUoQij3mtrX2lb8k4DjVmNheHQ==]
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:6DQPITUXWW+OMjBuI/lc7huzxdGGs9Tx:7QWopDSQhLIfPbZ4M/WJZLGNjgQyG6W7IpUfAuIGdVwb1fRrpsRTE2UK+v9dZCr3Cu5YBFAjhPkJtuvJtAf5vKHR]
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:cHNtNrgmu3uLgeG+fL5m8Yb+wlIRzzLm:rZuE+prdmF8vS5ezeW+OUexsSm6iSb7W1f9cvuUoDKkjBWxf]
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:/V7Uf4rYikJ0YW4/GGOG1w1SUoU4k+BY:UIh73fD0nnNxyP/KUtbIWY0gBBYmRCZv6ut2jdrzMcG1mcVYebO6MnRxbd7XqtYD6Zx9zKovQ7PuDs0=]
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: projecttracker
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: banillie/project_tracker
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: POST_DEPLOY
  name: django-migrate-job
  run_command: |
    python manage.py migrate --noinput
  source_dir: /
name: project-tracker
region: lon
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: banillie/project_tracker
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: project-tracker
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm project_tracker.wsgi
  source_dir: /