# Generated by Django 2.1.5 on 2021-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('organisation', models.CharField(choices=[('DfT', 'DFT'), ('HS2 LTD', 'HS2 LTD'), ('Highways England', 'HIGHWAYS ENGLAND'), ('MCA', 'MCA')], max_length=60)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('tele_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('live', models.BooleanField(default=True)),
            ],
        ),
    ]
