# Generated by Django 3.2 on 2022-02-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stakeholderorg',
            old_name='org',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stakeholders.stakeholderorg'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.stakeholderorg')),
            ],
        ),
        migrations.AddField(
            model_name='historicalstakeholder',
            name='group_drop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stakeholders.group'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='group_drop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stakeholders.group'),
        ),
    ]
