# Generated by Django 2.1.5 on 2021-09-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
