# Generated by Django 2.1.5 on 2021-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_auto_20210927_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='group',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='organisation',
            field=models.CharField(choices=[('DfT', 'DFT'), ('HS2 LTD', 'HS2 LTD'), ('Highways England', 'HIGHWAYS ENGLAND'), ('MCA', 'MCA')], max_length=60),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
