# Generated by Django 3.2 on 2022-02-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_auto_20220228_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstakeholder',
            old_name='group_drop',
            new_name='dft_group',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='group_drop',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='dft_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stakeholders.group'),
        ),
    ]
