# Generated by Django 3.2 on 2022-02-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_auto_20220228_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='DfTGroup',
        ),
    ]
