# Generated by Django 2.1.5 on 2021-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_auto_20210927_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='tele_no',
            field=models.IntegerField(),
        ),
    ]
