# Generated by Django 3.2 on 2022-02-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_rename_group_dftgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dftgroup',
            name='organisation',
        ),
    ]
