# Generated by Django 2.1.5 on 2021-09-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_auto_20210927_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='tele_no',
            field=models.TextField(max_length=1000),
        ),
    ]
