# Generated by Django 3.2 on 2023-02-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0005_remove_dftgroup_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstakeholder',
            name='my_dft_url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='my_dft_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
