# Generated by Django 2.1.5 on 2021-09-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0006_auto_20210927_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='tele_no',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
