# Generated by Django 2.1.5 on 2021-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0007_auto_20210927_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
