# Generated by Django 3.2 on 2021-10-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppdds', '0002_ppdd_slug'),
        ('projects', '0001_initial'),
        ('stakeholders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementWorkStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_stream', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('engagement_types', models.ManyToManyField(to='engagements.EngagementType')),
                ('engagement_workstreams', models.ManyToManyField(to='engagements.EngagementWorkStream')),
                ('ppdds', models.ManyToManyField(to='ppdds.PPDD')),
                ('projects', models.ManyToManyField(max_length=200, to='projects.Project')),
                ('stakeholders', models.ManyToManyField(to='stakeholders.Stakeholder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
