# Generated by Django 3.2 on 2022-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='topics',
            field=models.ManyToManyField(to='engagements.EngagementTopic'),
        ),
    ]
