# Generated by Django 3.2 on 2022-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_auto_20220203_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='engagement_types',
            field=models.ManyToManyField(blank=True, null=True, to='engagements.EngagementType'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagement_workstreams',
            field=models.ManyToManyField(blank=True, null=True, to='engagements.EngagementWorkStream'),
        ),
    ]
