# Generated by Django 3.2 on 2022-01-12 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagements', '0002_remove_engagement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='follow_up_date',
        ),
        migrations.AddField(
            model_name='engagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
