# Generated by Django 3.2 on 2022-02-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_auto_20220203_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='engagement_types',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='engagement_workstreams',
        ),
    ]
