# Generated by Django 3.2 on 2022-02-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0004_auto_20220203_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementtopic',
            options={'ordering': ('topic',)},
        ),
    ]
