# Generated by Django 2.1.5 on 2021-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210929_1115'),
        ('engagements', '0005_auto_20210929_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectengagement',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='projectengagement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='project',
        ),
        migrations.AddField(
            model_name='engagement',
            name='project',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='ProjectEngagement',
        ),
    ]
