# Generated by Django 2.1.5 on 2021-09-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0006_auto_20210930_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='ppdd',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='stakeholder',
        ),
        migrations.DeleteModel(
            name='Engagement',
        ),
    ]
