# Generated by Django 2.1.5 on 2021-09-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20210929_1115'),
        ('ppdds', '0001_initial'),
        ('stakeholders', '0001_initial'),
        ('engagements', '0007_auto_20210930_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('A', 'Assurance'), ('B', 'Benefits'), ('C', 'Carbon'), ('CC', 'Capability and Capacity'), ('CE', 'Cost Estimating and Benchmarking'), ('E', 'Engineering'), ('G', 'Goverance'), ('IT', 'Initial Triage'), ('LL', 'Lessons Learned'), ('OSR', 'Output Spec and Requirements'), ('PD', 'Planning and Dependencies'), ('PR', 'Portfolio Reporting'), ('RI', 'Risks and Issues')], max_length=20)),
                ('ws_type', models.CharField(blank=True, choices=[('AR', 'Assurance'), ('BR', 'Business Case Review'), ('CE', 'Cultural Enquiry'), ('LL', 'Lessons Learned Workshop'), ('L24', '24 Lessons Workshop')], max_length=20, null=True)),
                ('summary', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('ppdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppdds.PPDD')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.Engagement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='projects',
            field=models.ManyToManyField(through='engagements.EngagementProjects', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stakeholders.Stakeholder'),
        ),
    ]
