# Generated by Django 2.1.5 on 2021-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppdds', '0001_initial'),
        ('stakeholders', '0001_initial'),
        ('engagements', '0010_engagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='ppdd',
        ),
        migrations.AddField(
            model_name='engagement',
            name='ppdd',
            field=models.ManyToManyField(to='ppdds.PPDD'),
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='stakeholder',
        ),
        migrations.AddField(
            model_name='engagement',
            name='stakeholder',
            field=models.ManyToManyField(to='stakeholders.Stakeholder'),
        ),
    ]
