# Generated by Django 2.1.5 on 2021-10-01 10:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0011_auto_20211001_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='ppdd',
            new_name='ppdds',
        ),
        migrations.RenameField(
            model_name='engagement',
            old_name='stakeholder',
            new_name='stakeholders',
        ),
        migrations.AlterField(
            model_name='engagement',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Assurance'), ('B', 'Benefits'), ('C', 'Carbon'), ('CC', 'Capability and Capacity'), ('CE', 'Cost Estimating and Benchmarking'), ('E', 'Engineering'), ('G', 'Goverance'), ('IT', 'Initial Triage'), ('LL', 'Lessons Learned'), ('OSR', 'Output Spec and Requirements'), ('PD', 'Planning and Dependencies'), ('PR', 'Portfolio Reporting'), ('RI', 'Risks and Issues')], max_length=20),
        ),
    ]
