# Generated by Django 2.1.5 on 2021-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0012_auto_20211001_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementWorkStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='engagement',
            name='type',
            field=models.CharField(choices=[('A', 'Assurance'), ('B', 'Benefits'), ('C', 'Carbon'), ('CC', 'Capability and Capacity'), ('CE', 'Cost Estimating and Benchmarking'), ('E', 'Engineering'), ('G', 'Goverance'), ('IT', 'Initial Triage'), ('LL', 'Lessons Learned'), ('OSR', 'Output Spec and Requirements'), ('PD', 'Planning and Dependencies'), ('PR', 'Portfolio Reporting'), ('RI', 'Risks and Issues')], max_length=20),
        ),
    ]
