# Generated by Django 2.1.5 on 2021-10-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0013_auto_20211005_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngagementType',
        ),
        migrations.DeleteModel(
            name='EngagementWorkStream',
        ),
    ]
