# Generated by Django 2.1.5 on 2021-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0016_auto_20211005_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='projects',
            field=models.ManyToManyField(max_length=200, to='projects.Project'),
        ),
    ]
